-- Drop all tables
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS user_categories;
DROP TABLE IF EXISTS user_access_levels;
DROP TABLE IF EXISTS building_properties;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS geometries CASCADE;

