-- Create land use and fields

--Landuse is hierachical. Highest level is Order (Residential) then Group (Residential-Dwelling) then Class (Residential-Dwelling-Detached house)
--Fields could be linked when not mixed use Example: If user inputs class field (Detached-House) on front end then trigger on db automatically will populate group and order. If we go this route then a trigger is needed on the db both to run and remove this process.

-- Land use, single or mutiple classes?
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS landuse_mutiple_use boolean DEFAULT false;

-- Land use, how many different uses?
--TODO should there be an upper limite (yes) on number of landuses in a building seems unlikley to me more than 5 (ie. Shop, office, resi but shopping center/train station could be the exception to this )
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS landuse_number_of_uses SMALLINT CHECK (landuse_number_of_uses between 1 and 20) DEFAULT 1;


-- Land use NLUD class, this might be multiple and should match number of uses input. See page 34 of NLUD_documentation
-- Agriculture And Fisheries
-- Community Services
-- Defence
-- Forestry (not used)
-- Industry And Business
-- Minerals
-- Mixed (our definition)
-- Recreation And Leisure
-- Residential
-- Retail
-- Transport
-- Unused Land
-- Utilities And Infrastructure
-- Vacant And Derelict

CREATE TYPE landuse_order AS ENUM (
  'Agriculture And Fisheries',
  'Community Services',
  'Defence',
  'Industry And Business',
  'Minerals',
  'Mixed use',
  'Recreation And Leisure',
  'Residential',
  'Retail',
  'Transport',
  'Utilities And Infrastructure',
  'Vacant And Derelict',
  'None'
);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS landuse_order landuse_order DEFAULT 'None';

-- Land use NLUD group, can only be one  - prepopulated if mixed. See page 34 of NLUD_documentation§
-- Example of front end autofill drop down http://jsfiddle.net/p6qnczgv/
--TODO apostrophes in names need extra apostrophe
--TODO max length of enum is 63 characters..
ALTER TABLE buildings DROP COLUMN IF EXISTS landuse_group;

CREATE TYPE landuse_group AS ENUM (
'Agriculture-Agriculture And Fisheries',
'Fisheries-Agriculture And Fisheries',
'Medical and health care services-Community Services',
'Places of worship-Community Services',
'Education-Community Services',
'Community services-Community Services',
'Defence-Defence',
'Managed forest-Forestry',
'Un-managed forest-Forestry',
'Manufacturing-Industry And Business',
'Offices-Industry And Business',
'Storage-Industry And Business',
'Wholesale distribution-Industry And Business',
'Mineral workings and quarries-Minerals',
'Mixed',
'Outdoor amenity and open spaces-Recreation And Leisure',
'Amusement and show places-Recreation And Leisure',
'Libraries, museums and galleries-Recreation And Leisure',
'Sports facilities and grounds-Recreation And Leisure',
'Holiday parks and camps-Recreation And Leisure',
'Allotments and city farms-Recreation And Leisure',
'Dwellings-Residential',
'Hotels, boarding and guest houses-Residential',
'Residential institutions-Residential',
'Shops-Retail',
'Financial and professional services-Retail',
'Restaurants and cafes-Retail',
'Public houses and bars-Retail',
'Transport tracks and ways-Transport',
'Transport terminals and interchanges-Transport',
'Car parks-Transport',
'Vehicle storage-Transport',
'Goods and freight terminals-Transport',
'Waterways-Transport',
'Unused land-Unused Land',
'Energy production and distribution-Utilities And Infrastructure',
'Water storage and treatment-Utilities And Infrastructure',
'Refuse disposal-Utilities And Infrastructure',
'Cemeteries and crematoria-Utilities And Infrastructure',
'Post and telecommunications-Utilities And Infrastructure',
'Vacant-Vacant And Derelict',
'Derelict-Vacant And Derelict',
'None'
);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS landuse_group landuse_group DEFAULT 'None';


-- Land class NLUD order, can only be one
ALTER TABLE buildings DROP COLUMN IF EXISTS landuse_class;

CREATE TYPE landuse_class AS ENUM (
  "Car storage place - Car parks",
  "Community and health services - Community services",
  "Advertising hoarding - Community services",
  "Advertising places - Community services",
  "Approved school - Community services",
  "Arbitration court - Community services",
  "Borstal institution - Community services",
  "Church hall - Community services",
  "Civil Defense center - Community services",
  "Club meeting place - Community services",
  "Coastguard station - Community services",
  "Communication places - Community services",
  "Community center - Community services",
  "Community protection services - Community services",
  "Courts - Community services",
  "Detention places - Community services",
  "Fire station - Community services",
  "Justice administration places - Community services",
  "Law court - Community services",
  "Life boat station - Community services",
  "Police station - Community services",
  "Prison - Community services",
  "Prison rehabilitation center - Community services",
  "Protection places - Community services",
  "Public bath - Community services",
  "Public convenience - Community services",
  "Remand center - Community services",
  "Remand classifying center - Community services",
  "Remand home - Community services",
  "Sanitation places - Community services",
  "Social meeting places - Community services",
  "Tribunal place - Community services",
  "Building converted to more than one dwelling - Dwellings",
  "Bungalow - Dwellings",
  "Detached house - Dwellings",
  "Maisonette - Dwellings",
  "Movable dwelling site - Dwellings",
  "Non residential plus single dwelling - Dwellings",
  "Purpose built block of flats - Dwellings",
  "Residential caravan site - Dwellings",
  "Self contained residences - Dwellings",
  "Semi detached house - Dwellings",
  "Terraced house - Dwellings",
  "Adult education center - Education",
  "Archaeological site - Education",
  "College of further education - Education",
  "College of technology - Education",
  "Day nursery school - Education",
  "Education places - Education",
  "Infant school - Education",
  "Junior school - Education",
  "Middle school - Education",
  "Nature reserve - Education",
  "Nature reserves and sanctuaries - Education",
  "Nursery school - Education",
  "Observatory - Education",
  "Polytechnic - Education",
  "Pre primary schools - Education",
  "Primary schools - Education",
  "Research establishments - Education",
  "Research places - Education",
  "Secondary school - Education",
  "Secondary schools - Education",
  "Site of special scientific interest - Education",
  "Sixth form college - Education",
  "Special school - Education",
  "Specialized, higher and further education centers - Education",
  "Teacher training college - Education",
  "Technical college - Education",
  "University teaching establishment - Education",
  "Bank - Financial and professional services",
  "Betting office - Financial and professional services",
  "Building society office - Financial and professional services",
  "Financial service offices - Financial and professional services",
  "Insurance office - Financial and professional services",
  "Boarding house - Hotels, boarding and guest houses",
  "Group residences - Hotels, boarding and guest houses",
  "Hotel - Hotels, boarding and guest houses",
  "Residential club - Hotels, boarding and guest houses",
  "Rooming house - Hotels, boarding and guest houses",
  "Art gallery - Libraries, museums and galleries",
  "Galleries - Libraries, museums and galleries",
  "Lending library - Libraries, museums and galleries",
  "Libraries - Libraries, museums and galleries",
  "Libraries, museums and galleries - Libraries, museums and galleries",
  "Museum - Libraries, museums and galleries",
  "Reference - Libraries, museums and galleries",
  "Ambulance station - Medical and health care services",
  "Ante natal and post natal clinic - Medical and health care services",
  "Artificial limb and appliance hospital - Medical and health care services",
  "Auxiliary service centers medical - Medical and health care services",
  "Blood transfusion center - Medical and health care services",
  "Convalescent home - Medical and health care services",
  "Counselling agency - Medical and health care services",
  "Counselling places - Medical and health care services",
  "Dental hospital - Medical and health care services",
  "Dentist's surgery and consulting room - Medical and health care services",
  "Dispensary - Medical and health care services",
  "Doctor's surgery and consulting room - Medical and health care services",
  "Ear, nose and throat hospital - Medical and health care services",
  "Eye hospital - Medical and health care services",
  "Eye clinic and optician's surgery and consulting room - Medical and health care services",
  "Family planning clinic - Medical and health care services",
  "Foot clinic and chiropodist's surgery and consulting room - Medical and health care services",
  "Forensic medicine center - Medical and health care services",
  "General hospital - Medical and health care services",
  "Geriatric hospital - Medical and health care services",
  "Health care places - Medical and health care services",
  "Health center - Medical and health care services",
  "Hearing aid center - Medical and health care services",
  "Hospitals - Medical and health care services",
  "Isolation hospital - Medical and health care services",
  "Maternity hospital - Medical and health care services",
  "Medical auxiliary service centers - Medical and health care services",
  "Medical diagnosis and treatment centers - Medical and health care services",
  "Medical research establishments - Medical and health care services",
  "Medical research laboratory - Medical and health care services",
  "Mental hospital - Medical and health care services",
  "Mental clinic - Medical and health care services",
  "Nervous disorders clinic - Medical and health care services",
  "Occupational therapy and physiotherapy clinic - Medical and health care services",
  "Orthopaedic hospital - Medical and health care services",
  "Orthopaedic and rheumatic clinic - Medical and health care services",
  "Radiography center - Medical and health care services",
  "Surgeon's surgery and consulting room - Medical and health care services",
  "Places of worship - Places of worship",
  "Public house - Public houses, bars and nightclubs",
  "Refuse disposal places - Refuse disposal",
  "Refuse disposal plant - Refuse disposal",
  "Refuse tip - Refuse disposal",
  "Residences - Residential",
  "Barracks - Residential institutions",
  "Children's home - Residential institutions",
  "Communal homes - Residential institutions",
  "Handicapped and disabled people's home - Residential institutions",
  "Non medical care places - Residential institutions",
  "Non medical homes - Residential institutions",
  "Old people's home - Residential institutions",
  "Residential retreat - Residential institutions",
  "School boarding house - Residential institutions",
  "Staff hostel - Residential institutions",
  "Catering places - Restaurants and cafes",
  "Restaurant - Restaurants and cafes",
  "Catering service places - Retail",
  "Retail distribution places - Retail",
  "Retail distribution and servicing places - Retail",
  "Baker's shop - Shops",
  "Beauty salon - Shops",
  "Boot and shoe repair establishment - Shops",
  "Butcher's shop - Shops",
  "Caravan sales place - Shops",
  "Cash and carry store - Shops",
  "Cats meat shop - Shops",
  "Clothing and footwear shop - Shops",
  "Confectionery, tobacco and newspaper shop - Shops",
  "Dairy shop - Shops",
  "Department store - Shops",
  "Dry cleaning and clothing repair establishment - Shops",
  "Duplicating and copying center - Shops",
  "Electricity showroom - Shops",
  "Fish shop - Shops",
  "Food and drink shops - Shops",
  "Fried fish shop - Shops",
  "Frozen food shop - Shops",
  "Gas showroom - Shops",
  "General stores - Shops",
  "Green grocer's shop - Shops",
  "Grocery and provision - Shops",
  "Hairdresser's shop - Shops",
  "Hot food shop - Shops",
  "Household goods shop - Shops",
  "Household goods shops and showrooms - Shops",
  "Hybrid shops and stores - Shops",
  "Hypermarket - Shops",
  "Launderette - Shops",
  "Laundry (cleaning only) - Shops",
  "Laundry, cleaning and repairing shop (receiving) - Shops",
  "Maintenance and repair places - Shops",
  "Motor vehicle dealer display area - Shops",
  "Motor vehicle goods shops and filling stations - Shops",
  "Motor vehicle maintenance and repair places - Shops",
  "Motor vehicle repair garage - Shops",
  "Motor vehicle sales - Shops",
  "Motor vehicle spare parts and accessories - Shops",
  "Motor vehicle testing station - Shops",
  "Off license - Shops",
  "Personal and household goods repair and cleaning places - Shops",
  "Pet animal and bird shop - Shops",
  "Petrol and oil filling station - Shops",
  "Photographic service shop - Shops",
  "Post office - Shops",
  "Retail market place - Shops",
  "Supermarket - Shops",
  "Ticket agency - Shops",
  "Travel agency - Shops",
  "Tripe shop - Shops",
  "Tire retailing and fitting place - Shops",
  "Undertaker - Shops",
  "Unused buildings - . Previously developed land",
  "Agricultural research establishment - Agriculture",
  "Agriculture and fisheries places - Agriculture",
  "Animal artificial insemination center - Agriculture",
  "Animal boarding establishment - Agriculture",
  "Animal breeding places - Agriculture",
  "Animal clipping and manicure establishment - Agriculture",
  "Animal dipping place - Agriculture",
  "Animal living places - Agriculture",
  "Animal milking places - Agriculture",
  "Animal product processing places - Agriculture",
  "Animal product waste store - Agriculture",
  "Animal product waste treatment places - Agriculture",
  "Animal products waste handling places - Agriculture",
  "Animal rearing places - Agriculture",
  "Animal service places - Agriculture",
  "Animal service places - Agriculture",
  "Animal shearing places - Agriculture",
  "Animal slaughtering places - Agriculture",
  "Animal stunning and killing places - Agriculture",
  "Animal welfare places - Agriculture",
  "Arable farm places - Agriculture",
  "Bedding and waste removal - Agriculture",
  "Blacksmith premises - Agriculture",
  "Crop conditioning grading and storage places - Agriculture",
  "Crop processing places - Agriculture",
  "Cultivated places 6 - Agriculture",
  "Egg grading place - Agriculture",
  "Feed handling places - Agriculture",
  "Feed preparation place - Agriculture",
  "Feed storage place - Agriculture",
  "Feeding - Agriculture",
  "Fish sorting place - Agriculture",
  "Glass house - Agriculture",
  "Green forage crops place - Agriculture",
  "Green forage crops store - Agriculture",
  "Horticultural places - Agriculture",
  "Isolation (animal living place) - Agriculture",
  "Knackering place - Agriculture",
  "Milk extraction place - Agriculture",
  "Milk treatment place - Agriculture",
  "Mill and mix building - Agriculture",
  "Packing and sorting (crop processing place) - Agriculture",
  "Packing places (animal products) - Agriculture",
  "Parturition place - Agriculture",
  "Permanent pasture - Agriculture",
  "Processing place (animal slaughtering place) - Agriculture",
  "Pulse crops place - Agriculture",
  "Pulse crops store - Agriculture",
  "Quarantine place, animal - Agriculture",
  "Root crops place - Agriculture",
  "Root crops store - Agriculture",
  "Soft fruit place - Agriculture",
  "Vegetable (crop conditioning and storage) - Agriculture",
  "Veterinary hospital - Agriculture",
  "Veterinary surgery - Agriculture",
  "Weighing place - Agriculture",
  "Wool grading place - Agriculture",
  "Wool removal place - Agriculture",
  "Amusement places - Amusement and show places",
  "Aquarium - Amusement and show places",
  "Bingo club - Amusement and show places",
  "Broadcasting, filming and sound recording studio - Amusement and show places",
  "Children's playground - Amusement and show places",
  "Cinema - Amusement and show places",
  "Circus - Amusement and show places",
  "Concert arena - Amusement and show places",
  "Countryside interpretation center - Amusement and show places",
  "Dance hall - Amusement and show places",
  "Display arena - Amusement and show places",
  "Fun fair - Amusement and show places",
  "Gaming club - Amusement and show places",
  "Night club - Amusement and show places",
  "Show places - Amusement and show places",
  "Theatre - Amusement and show places",
  "Cemetery - Cemeteries and crematoria",
  "Chapel of rest - Cemeteries and crematoria",
  "Crematorium - Cemeteries and crematoria",
  "Dead bodies disposal places - Cemeteries and crematoria",
  "Dead bodies storage places - Cemeteries and crematoria",
  "Mortuary - Cemeteries and crematoria",
  "Defense establishments - Defense",
  "Defense training places - Defense",
  "Abandoned building - Derelict",
  "Ruined building - Derelict",
  "Waste heap or tip - Derelict",
  "District heating places - Energy production and distribution",
  "District heating plant - Energy production and distribution",
  "Electricity cableway - Energy production and distribution",
  "Electricity distribution places - Energy production and distribution",
  "Electricity production places - Energy production and distribution",
  "Electricity supply places - Energy production and distribution",
  "Electricity transformer station - Energy production and distribution",
  "Gas distribution places - Energy production and distribution",
  "Gas holder - Energy production and distribution",
  "Gas pressure control station - Energy production and distribution",
  "Gas production and storage places - Energy production and distribution",
  "Gas supply places - Energy production and distribution",
  "Gas works - Energy production and distribution",
  "Hydro electricity generating station - Energy production and distribution",
  "Oil pumping station - Energy production and distribution",
  "Pipeline - Energy production and distribution",
  "Thermal electricity generating station - Energy production and distribution",
  "Fish farm - Fisheries",
  "Fishery places - Fisheries",
  "Hatchery - Fisheries",
  "Net fishery place - Fisheries",
  "Aerial ropeway - Goods and freight handling",
  "Air freight terminal - Goods and freight handling",
  "Container depot - Goods and freight handling",
  "Conveyor - Goods and freight handling",
  "Customs depot - Goods and freight handling",
  "Docks - Goods and freight handling",
  "Goods handling places - Goods and freight handling",
  "Lift - Goods and freight handling",
  "Lorry transhipment park - Goods and freight handling",
  "Mechanical handling places - Goods and freight handling",
  "Railway goods siding - Goods and freight handling",
  "Railway goods yard - Goods and freight handling",
  "Railway sorting depot - Goods and freight handling",
  "Terminals and interchanges for goods - Goods and freight handling",
  "Youth hostel - Holiday camps",
  "Telegraph and telephone apparatus and equipment manufacturing - Manufacturing",
  "Abrasives and other building materials manufacturing place - Manufacturing",
  "Aerospace equipment manufacturing or repairing place - Manufacturing",
  "Agricultural machinery manufacturing place - Manufacturing",
  "Aluminum and aluminum alloy manufacturing - Manufacturing",
  "Animal and poultry food manufacturing place - Manufacturing",
  "Bacon curing, meat and fish product manufacturing place - Manufacturing",
  "Bedding and soft furnishings manufacturing place - Manufacturing",
  "Biscuit manufacturing - Manufacturing",
  "Bolts, nuts, screws, rivets etc. manufacturing place - Manufacturing",
  "Bread and flour confectionery manufacturing place - Manufacturing",
  "Brewery - Manufacturing",
  "Bricks, fireclay and refractory goods manufacturing place - Manufacturing",
  "Bricks, pottery, glass, cement manufacturing places - Manufacturing",
  "Brushes and brooms manufacturing place - Manufacturing",
  "Can and metal box manufacturing place - Manufacturing",
  "Carpet manufacturing place - Manufacturing",
  "Cement manufacturing place - Manufacturing",
  "Chemical and allied industries manufacturing places - Manufacturing",
  "Clothing and footwear manufacturing places 5C - Manufacturing",
  "Coal and petroleum processing places - Manufacturing",
  "Coal, oil and metal processing places - Manufacturing",
  "Cocoa, chocolate and sugar confectionery manufacturing place - Manufacturing",
  "Coke ovens and solid fuel manufacturing place - Manufacturing",
  "Construction and demolition site - Manufacturing",
  "Construction and earth moving equipment manufacturing place - Manufacturing",
  "Construction places - Manufacturing",
  "Construction places - Manufacturing",
  "Copper, brass and other copper alloy manufacturing place - Manufacturing",
  "Cutlery and plated tableware manufacturing place - Manufacturing",
  "Dresses, lingerie, infants wear etc. manufacturing place 5C - Manufacturing",
  "Dyestuffs and pigments manufacturing place - Manufacturing",
  "Electrical engineering places - Manufacturing",
  "Electrical machinery manufacturing place - Manufacturing",
  "Electronic computers manufacturing place - Manufacturing",
  "Engineering places - Manufacturing",
  "Explosives and fireworks manufacturing place - Manufacturing",
  "Fertilizer manufacturing place - Manufacturing",
  "Food, drink and tobacco manufacturing place - Manufacturing",
  "Footwear manufacturing place - Manufacturing",
  "Fruit and vegetable product manufacturing place - Manufacturing",
  "Fur goods manufacturing place - Manufacturing",
  "Furniture and upholstery manufacturing place - Manufacturing",
  "General chemical manufacturing place - Manufacturing",
  "Glass manufacturing place - Manufacturing",
  "Grain mill - Manufacturing",
  "Hats, cap and millinery manufacturing place - Manufacturing",
  "Hosiery and other knitted goods manufacturing place - Manufacturing",
  "Industrial research laboratory - Manufacturing",
  "Industrial services equipment manufacturing place - Manufacturing",
  "Instrument engineering places - Manufacturing",
  "Insulated wires and cables manufacturing place - Manufacturing",
  "Iron and steel manufacturing place - Manufacturing",
  "Jeweler and precious metal manufacturing place - Manufacturing",
  "Jute manufacturing place - Manufacturing",
  "Knitted goods manufacturing place - Manufacturing",
  "Lace manufacturing place - Manufacturing",
  "Lead manufacturing place - Manufacturing",
  "Leather (tanning and dressing) and fellmongery place - Manufacturing",
  "Leather and fur goods manufacturing places - Manufacturing",
  "Leather goods manufacturing place - Manufacturing",
  "Linoleum, plastics floor covering, leather cloth manufacturing place - Manufacturing",
  "Locomotives and railway track equipment manufacturing place - Manufacturing",
  "Lubricating oil and grease manufacturing place - Manufacturing",
  "Made up textile manufacturing place - Manufacturing",
  "Man made fiber production manufacturing place - Manufacturing",
  "Manufacturing research establishments - Manufacturing",
  "Manufacturing storage place - Manufacturing",
  "Manufacturing storage places - Manufacturing",
  "Manufacturing waste disposal places - Manufacturing",
  "Manufacturing waste tip - Manufacturing",
  "Mechanical engineering places - Manufacturing",
  "Mechanical handling equipment manufacturing place - Manufacturing",
  "Metal processing places (basic forms) - Manufacturing",
  "Metal working machine tools manufacturing place - Manufacturing",
  "Milk and milk product manufacturing place - Manufacturing",
  "Mineral oil refinery - Manufacturing",
  "Miscellaneous goods manufacturing place - Manufacturing",
  "Miscellaneous stationers goods manufacturing place - Manufacturing",
  "Miscellaneous wood and cork manufacturing place - Manufacturing",
  "Motor cycle, tricycle and pedal cycle manufacturing place - Manufacturing",
  "Motor vehicle manufacturing place - Manufacturing",
  "Narrow fabric manufacturing place - Manufacturing",
  "Office machinery manufacturing place - Manufacturing",
  "Ordnance and small arms manufacturing place - Manufacturing",
  "Overalls and men's shirts and underwear manufacturing place 5C - Manufacturing",
  "Paint manufacturing place - Manufacturing",
  "Paper and board manufacturing place - Manufacturing",
  "Paper, printing and publishing works - Manufacturing",
  "Periodical and newspaper printing and publishing works - Manufacturing",
  "Pharmaceutical chemicals and preparation manufacturing place - Manufacturing",
  "Pottery manufacturing place - Manufacturing",
  "Prime movers manufacturing place - Manufacturing",
  "Pumps, valves and compressor manufacturing place - Manufacturing",
  "Radio and electronic capital goods manufacturing place - Manufacturing",
  "Radio, radar and electronic capital goods manufacturing place - Manufacturing",
  "Railway carriages and wagons and trams manufacturing place - Manufacturing",
  "Rope, twine and net manufacturing place - Manufacturing",
  "Rubber goods manufacturing place - Manufacturing",
  "Shipbuilding and marine engineering place - Manufacturing",
  "Shop and office fittings manufacturing place - Manufacturing",
  "Small tools, implements and gauges manufacturing place - Manufacturing",
  "Soft drinks manufacturing place - Manufacturing",
  "Stationery manufacturing place - Manufacturing",
  "Sugar refinery - Manufacturing",
  "Surgical instruments and appliances manufacturing place - Manufacturing",
  "Synthetic resins, plastics and synthetic rubber manufacturing - Manufacturing",
  "Tailored outerwear manufacturing place - Manufacturing",
  "Textile finishing place - Manufacturing",
  "Textile machinery and accessories manufacturing place - Manufacturing",
  "Textile manufacturing places - Manufacturing",
  "Timber and furniture works - Manufacturing",
  "Timber furniture, paper, printing and publishing works - Manufacturing",
  "Timber works - Manufacturing",
  "Tobacco manufacturing place - Manufacturing",
  "Toilet preparation manufacturing place - Manufacturing",
  "toys, games, children's carriages and sports equipment - Manufacturing",
  "Vegetable, animal oil and fat manufacturing place - Manufacturing",
  "Vehicle engineering places - Manufacturing",
  "Watches and clocks manufacturing place - Manufacturing",
  "Weatherproof outerwear manufacturing place - Manufacturing",
  "Weaving of cotton, linen and man made fibers manufacturing place - Manufacturing",
  "Wheeled tractor manufacturing place - Manufacturing",
  "Wire manufacturing place - Manufacturing",
  "Wooden containers and baskets manufacturing place - Manufacturing",
  "Woolen and worsted manufacturing place - Manufacturing",
  "Packaging products of paper and associated materials - Manufacturing",
  "Broadcast receiving and sound reproducing equipment - Manufacturing",
  "Soap, detergent and fat splitting and distillation manufacturing - Manufacturing",
  "Photographic and document copying equipment manufacturing - Manufacturing",
  "Scientific and industrial instruments and systems manufacturing - Manufacturing",
  "Spinning and doubling (cotton and flax systems) manufacturing - Manufacturing",
  "Electric appliances primarily for domestic use manufacturing - Manufacturing",
  "Clothing, textiles, leather, footwear and fur goods manufacturing - Manufacturing",
  "Business discussion places - Offices",
  "Business meeting places - Offices",
  "Business meeting places - Offices",
  "Central government administration office - Offices",
  "General offices - Offices",
  "Local government administration office - Offices",
  "Manufacturing administration office - Offices",
  "Offices OF - Offices",
  "Professional services office - Offices",
  "Studio - Offices",
  "Aircraft hangar - Other vehicle storage",
  "Bus depot - Other vehicle storage",
  "Coach depot - Other vehicle storage",
  "Long stay lorry park - Other vehicle storage",
  "Railway sidings - Other vehicle storage",
  "Ancient monument - Outdoor amenity and open spaces",
  "Direction finding places - Post and telecommunications",
  "Direction finding transmitter - Post and telecommunications",
  "Navigational light beacon - Post and telecommunications",
  "Postal service places - Post and telecommunications",
  "Postal service, signaling and telecommunications places - Post and telecommunications",
  "Postal sorting depot - Post and telecommunications",
  "Radar beacon - Post and telecommunications",
  "Radar places - Post and telecommunications",
  "Radar station - Post and telecommunications",
  "Radio and television mast - Post and telecommunications",
  "Radio station - Post and telecommunications",
  "Satellite communication station - Post and telecommunications",
  "Signaling station - Post and telecommunications",
  "Telephone cableway - Post and telecommunications",
  "Telephone exchange - Post and telecommunications",
  "Telephone kiosk - Post and telecommunications",
  "Television and radio broadcasting places - Post and telecommunications",
  "Television station - Post and telecommunications",
  "Amenity, amusement and show places - Recreation and leisure",
  "Recreation and leisure places - Recreation and leisure",
  "Animal training and competing places - Sports facilities",
  "Athletic games arenas - Sports facilities",
  "Athletic ground - Sports facilities",
  "Badminton court - Sports facilities",
  "Ball game courses - Sports facilities",
  "Boating facilities - Sports facilities",
  "Combative sports place - Sports facilities",
  "Cycling circuit - Sports facilities",
  "Dog racing track - Sports facilities",
  "Dog trials area - Sports facilities",
  "Golf driving range - Sports facilities",
  "Gymnasium - Sports facilities",
  "Hockey ground - Sports facilities",
  "Horse show jumping, dressage and trotting arena - Sports facilities",
  "Horse training area - Sports facilities",
  "Ice rink - Sports facilities",
  "Miniature golf course - Sports facilities",
  "Motor vehicle racing track - Sports facilities",
  "Rock climbing - Sports facilities",
  "Roller skating rink - Sports facilities",
  "Rowing water - Sports facilities",
  "Rugby football ground - Sports facilities",
  "Sailing - Sports facilities",
  "Small arms range - Sports facilities",
  "Squash court - Sports facilities",
  "Swimming and bathing - Sports facilities",
  "Swimming baths - Sports facilities",
  "Target shooting places - Sports facilities",
  "Ten pin bowling alley - Sports facilities",
  "Water recreation places - Sports facilities",
  "Water skiing place - Sports facilities",
  "Water sport places - Sports facilities",
  "Watercraft places - Sports facilities",
  "Agricultural machinery store - Storage",
  "Builders yard - Storage",
  "Building equipment store - Storage",
  "Bulk material stores - Storage",
  "Cleaning materials store - Storage",
  "Engineering equipment store - Storage",
  "Equipment stores - Storage",
  "Furniture depository - Storage",
  "General goods store - Storage",
  "Industrial and office machinery store - Storage",
  "Material stores - Storage",
  "Refrigerated store - Storage",
  "Sports equipment store - Storage",
  "Storage - Storage",
  "Storage places for vehicles - Transport",
  "Transport tracks and places - Transport",
  "Aerial ropeway passenger terminal - Transport terminals and interchanges",
  "Air passenger terminal - Transport terminals and interchanges",
  "Airport - Transport terminals and interchanges",
  "Bus station - Transport terminals and interchanges",
  "Bus stop - Transport terminals and interchanges",
  "Car park - Transport terminals and interchanges",
  "Coach station - Transport terminals and interchanges",
  "Land transport places - Transport terminals and interchanges",
  "Railway station - Transport terminals and interchanges",
  "Ship passenger terminal - Transport terminals and interchanges",
  "Terminals and interchanges for people - Transport terminals and interchanges",
  "Utility services - Utilities and infrastructure",
  "Vacant building - Vacant",
  "Sewage disposal places - Water storage and treatment",
  "Sewage draining places - Water storage and treatment",
  "Sewage farm - Water storage and treatment",
  "Sewage pumping station - Water storage and treatment",
  "Sewage treatment places - Water storage and treatment",
  "Sewage treatment works - Water storage and treatment",
  "Water distribution places - Water storage and treatment",
  "Water extraction places - Water storage and treatment",
  "Water intake from rivers or streams - Water storage and treatment",
  "Water intake from springs - Water storage and treatment",
  "Water intake from underground sources - Water storage and treatment",
  "Water pumping station - Water storage and treatment",
  "Water storage and treatment places - Water storage and treatment",
  "Water supply places - Water storage and treatment",
  "Water tower - Water storage and treatment",
  "Water treatment works - Water storage and treatment",
  "Boatyard - Waterways",
  "Mooring - Waterways",
  "Storage places for water craft - Waterways",
  "Water tracks - Waterways",
  "Water transport places - Waterways",
  "Water transport tracks - Waterways",
  "Agricultural machinery dealer's place - Wholesale distribution",
  "Builders merchant's place - Wholesale distribution",
  "Bulk dealing places - Wholesale distribution",
  "Coal and oil dealer's place - Wholesale distribution",
  "Corn, seed and agricultural supplies dealer's place - Wholesale distribution",
  "Dealing in industrial materials, machinery and livestock places - Wholesale distribution",
  "Food and drink wholesaling places - Wholesale distribution",
  "Grocery and provisions confectionery and drinks wholesaling - Wholesale distribution",
  "Hides, skin and leather dealer's place - Wholesale distribution",
  "Horses and livestock dealer - Wholesale distribution",
  "Horses and livestock dealing places - Wholesale distribution",
  "Industrial materials and other machinery dealing places - Wholesale distribution",
  "Petroleum products wholesaling place - Wholesale distribution",
  "Scrap and waste dealer - Wholesale distribution",
  "Timber dealer's place - Wholesale distribution",
  "Wholesale distribution places - Wholesale distribution"
);
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS landuse_class landuse_class DEFAULT 'None';
